// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyhiegoyuypmuveqtlwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5aGllZ295dXlwbXV2ZXF0bHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTQxOTYsImV4cCI6MjA3MjEzMDE5Nn0.TDD-uOEJz2P-v9heNJ6rnospYlSSuMpRGNR8txAvLlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});